<?php

/**
 * BaseThread
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $textbody
 * @property integer $content_id
 * @property integer $topic_id
 * @property Content $Content
 * @property Topic $Topic
 * 
 * @method string  getTitle()      Returns the current record's "title" value
 * @method string  getTextbody()   Returns the current record's "textbody" value
 * @method integer getContentId()  Returns the current record's "content_id" value
 * @method integer getTopicId()    Returns the current record's "topic_id" value
 * @method Content getContent()    Returns the current record's "Content" value
 * @method Topic   getTopic()      Returns the current record's "Topic" value
 * @method Thread  setTitle()      Sets the current record's "title" value
 * @method Thread  setTextbody()   Sets the current record's "textbody" value
 * @method Thread  setContentId()  Sets the current record's "content_id" value
 * @method Thread  setTopicId()    Sets the current record's "topic_id" value
 * @method Thread  setContent()    Sets the current record's "Content" value
 * @method Thread  setTopic()      Sets the current record's "Topic" value
 * 
 * @package    HELLO_WORLD
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseThread extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('thread');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('textbody', 'string', 2550, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '2550',
             ));
        $this->hasColumn('content_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('topic_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Content', array(
             'local' => 'content_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Topic', array(
             'local' => 'topic_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}