<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer            getUserId()      Returns the current record's "user_id" value
 * @method string             getFirstName()   Returns the current record's "first_name" value
 * @method string             getLastName()    Returns the current record's "last_name" value
 * @method string             getEmail()       Returns the current record's "email" value
 * @method sfGuardUser        getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method sfGuardUserProfile setUserId()      Sets the current record's "user_id" value
 * @method sfGuardUserProfile setFirstName()   Sets the current record's "first_name" value
 * @method sfGuardUserProfile setLastName()    Sets the current record's "last_name" value
 * @method sfGuardUserProfile setEmail()       Sets the current record's "email" value
 * @method sfGuardUserProfile setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    OpenBRD
 * @subpackage model
 * @author     Ralph B. Magnus
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('first_name', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('last_name', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('email', 'string', 75, array(
             'type' => 'string',
             'length' => '75',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}