<?php

/**
 * BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $shortdesc
 * @property string $textbody
 * @property boolean $has_content
 * 
 * @method string  getTitle()       Returns the current record's "title" value
 * @method string  getShortdesc()   Returns the current record's "shortdesc" value
 * @method string  getTextbody()    Returns the current record's "textbody" value
 * @method boolean getHasContent()  Returns the current record's "has_content" value
 * @method Page    setTitle()       Sets the current record's "title" value
 * @method Page    setShortdesc()   Sets the current record's "shortdesc" value
 * @method Page    setTextbody()    Sets the current record's "textbody" value
 * @method Page    setHasContent()  Sets the current record's "has_content" value
 * 
 * @package    OpenBRD
 * @subpackage model
 * @author     Ralph B. Magnus
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('shortdesc', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('textbody', 'string', 2550, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '2550',
             ));
        $this->hasColumn('has_content', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}