<?php

/**
 * Basesf_guard_user_profile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property varchar $first_name
 * @property varchar $last_name
 * @property date $birthday
 * @property sfGuardUser $User
 * 
 * @method integer               getUserId()     Returns the current record's "user_id" value
 * @method varchar               getFirstName()  Returns the current record's "first_name" value
 * @method varchar               getLastName()   Returns the current record's "last_name" value
 * @method date                  getBirthday()   Returns the current record's "birthday" value
 * @method sfGuardUser           getUser()       Returns the current record's "User" value
 * @method sf_guard_user_profile setUserId()     Sets the current record's "user_id" value
 * @method sf_guard_user_profile setFirstName()  Sets the current record's "first_name" value
 * @method sf_guard_user_profile setLastName()   Sets the current record's "last_name" value
 * @method sf_guard_user_profile setBirthday()   Sets the current record's "birthday" value
 * @method sf_guard_user_profile setUser()       Sets the current record's "User" value
 * 
 * @package    OpenBRD
 * @subpackage model
 * @author     Ralph B. Magnus
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Basesf_guard_user_profile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('first_name', 'varchar', 25, array(
             'type' => 'varchar',
             'length' => '25',
             ));
        $this->hasColumn('last_name', 'varchar', 25, array(
             'type' => 'varchar',
             'length' => '25',
             ));
        $this->hasColumn('birthday', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}