<?php

/**
 * BaseDirective
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $misc
 * @property Doctrine_Collection $DirectiveContent
 * @property Doctrine_Collection $DirectiveTopic
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getMisc()             Returns the current record's "misc" value
 * @method Doctrine_Collection getDirectiveContent() Returns the current record's "DirectiveContent" collection
 * @method Doctrine_Collection getDirectiveTopic()   Returns the current record's "DirectiveTopic" collection
 * @method Directive           setName()             Sets the current record's "name" value
 * @method Directive           setMisc()             Sets the current record's "misc" value
 * @method Directive           setDirectiveContent() Sets the current record's "DirectiveContent" collection
 * @method Directive           setDirectiveTopic()   Sets the current record's "DirectiveTopic" collection
 * 
 * @package    OpenBRD
 * @subpackage model
 * @author     Ralph B. Magnus
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDirective extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('directive');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('misc', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Content as DirectiveContent', array(
             'local' => 'id',
             'foreign' => 'directive_id'));

        $this->hasMany('Topic as DirectiveTopic', array(
             'local' => 'id',
             'foreign' => 'directive_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}