<?php

/**
 * BaseUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property sfGuardUser $User
 * 
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method string      getFirstName()  Returns the current record's "first_name" value
 * @method string      getLastName()   Returns the current record's "last_name" value
 * @method string      getEmail()      Returns the current record's "email" value
 * @method sfGuardUser getUser()       Returns the current record's "User" value
 * @method UserProfile setUserId()     Sets the current record's "user_id" value
 * @method UserProfile setFirstName()  Sets the current record's "first_name" value
 * @method UserProfile setLastName()   Sets the current record's "last_name" value
 * @method UserProfile setEmail()      Sets the current record's "email" value
 * @method UserProfile setUser()       Sets the current record's "User" value
 * 
 * @package    OpenBRD
 * @subpackage model
 * @author     Ralph B. Magnus
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_profile');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('first_name', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('last_name', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}