<?php

/**
 * sf_guard_user_profile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    OpenBRD
 * @subpackage model
 * @author     Ralph B. Magnus
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class sf_guard_user_profile extends Basesf_guard_user_profile
{
}
