<?php

/**
 * Topic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    HELLO_WORLD
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Topic extends BaseTopic
{

	public function getTopicThreads()
        {
                $q = Doctrine_Query::create()
                  ->from('Thread t')
                  ->where('t.topic_id = ?', $this->getId());

                return Doctrine_Core::getTable('Thread')->getThreads($q);
        }

}
