# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

content:
  class:   sfDoctrineRouteCollection
  options: { model: Content }

user:
  class:   sfDoctrineRouteCollection
  options: { model: User }

topic:
  class:   sfDoctrineRouteCollection
  options: { model: Topic }

thread:
  class:   sfDoctrineRouteCollection
  options: { model: Thread }

selected-thread:
  url:   /thread/:id
  class:   sfDoctrineRoute
  options: { model: Thread, type: object }
  param:   { module: thread, action: show }
  requirements:
    id: \d+
    sf_method: [get]

content-owner:
  url:	 /user/:id
  class:   sfDoctrineRoute
  options: { model: User, type: object }
  param:   { module: user, action: show }
  requirements:
    id: \d+
    sf_method: [get]

# default rules
homepage:
  url:   /
  param: { module: content, action: index }

# generic rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
