Directive:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: true }
    misc: { type: string(255) }

sfGuardUserProfile:
  actAs: { Timestampable: ~ }
  columns:
    id:          { type: integer, primary: true, autoincrement: true }
    user_id:	 { type: integer(4) }
    firstname:   { type: string(20) }
    lastname:    { type: string(20) }
    email:       { type: string(75) }
  relations:
    sfGuardUser: { class: sfGuardUser, local: user_id, foreign: id, type: one, foreignType: one, foreignAlias: Profile }

Content:
  actAs: { Timestampable: ~ }
  columns:
    name:         { type: string(255), notnull: true }
    shortdesc:    { type: string(255), notnull: true }
    longdesc:     { type: string(2550), notnull: true }
    type:         { type: enum, values: [video, audio, document] }
    full_content: { type: string(255), notnull: true }
    prev_content: { type: string(255), notnull: true }
    thmb_content: { type: string(255), notnull: true }
    user_id:      { type: integer(4), notnull: true }
    directive_id: { type: integer, notnull: true }
    fullaccess_id:  { type: integer(4) }
    prevaccess_id:  { type: integer(4) }
  relations:     
    Directive:    { onDelete: CASCADE, local: directive_id, foreign: id, foreignAlias: DirectiveContent } 
    User:         { class: sfGuardUser, local: user_id, foreign: id, foreignAlias: UserContent }
    FullAccess:   { class: sfGuardPermission, local: fullaccess_id, foreign: id, foreignAlias: RankingFullAccess }
    PrevAccess:	  { class: sfGuardPermission, local: prevaccess_id, foreign: id, foreignAlias: RankingPrevAccess }
    
Page:
  actAs: { Timestampable: ~ }
  columns:
    title:         { type: string(255), notnull: true }
    shortdesc:     { type: string(255), notnull: true }
    textbody:      { type: string(2550), notnull: true }
    has_content:   { type: boolean, default: false }

Topic:
  actAs: { Timestampable: ~ }
  columns:
    title:        { type: string(255), notnull: true }
    directive_id: { type: integer, notnull: true }
  relations:
    Directive:    { onDelete: CASCADE, local: directive_id, foreign: id, foreignAlias: DirectiveTopic }

Thread:
  actAs: { Timestampable: ~ }
  columns:
    title:        { type: string(255), notnull: true }
    textbody:     { type: string(2550), notnull: true }
    content_id:   { type: integer }
    topic_id:     { type: integer }
    user_id:	  { type: integer(4) }
  relations:
    Content:      { onDelete: CASCADE, local: content_id, foreign: id, foreignAlias: ContentThread }
    Topic:        { onDelete: CASCADE, local: topic_id, foreign: id, foreignAlias: TopicThread } 
    User:         { class: sfGuardUser, local: user_id, foreign: id, foreignAlias: UserContent }    

Reply:
  actAs: { Timestampable: ~ }
  columns:
    textbody:	  { type: string(2550), notnull: true }
    thread_id:    { type: integer }
    user_id:      { type: integer(4) }
  relations: 
    Thread:       { onDelete: CASCADE, local: thread_id, foreign: id, foreignAlias: ReplyThread }
    User:         { class: sfGuardUser, local: user_id, foreign: id, foreignAlias: UserContent }

