Directive:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: true }
    misc: { type: string(255) }

Ranking:
  actAs: { Timestampable: ~ }
  columns:
    name:  { type: string(255), notnull: true, unique: true }
    prio:  { type: integer, notnull: true }
    icon:  { type: string(255), notnull: true, unique: true }

User:
  actAs: { Timestampable: ~ }
  columns:
    username:     { type: string(255), notnull: true, unique: true }
    password:     { type: string(255), notnull: true }
    regkey:       { type: string(255), notnull: true, unique: true }
    role:         { type: enum, values: [administrator, moderator, user] }
    directive_id: { type: integer, notnull: true } 
    ranking_id:   { type: integer, notnull: true }
  relations:
    Directive:    { onDelete: CASCADE, local: directive_id, foreign: id, foreignAlias: DirectiveUser }
    Ranking:      { onDelete: CASCADE, local: ranking_id, foreign: id, foreignAlias: RankingUser }

Content:
  actAs: { Timestampable: ~ }
  columns:
    name:         { type: string(255), notnull: true }
    shortdesc:    { type: string(255), notnull: true }
    longdesc:     { type: string(2550), notnull: true }
    type:         { type: enum, values: [video, audio, document] }
    full_content: { type: string(255), notnull: true }
    prev_content: { type: string(255), notnull: true }
    thmb_content: { type: string(255), notnull: true }
    user_id:      { type: integer, notnull: true }
    directive_id: { type: integer, notnull: true }
    fullaccess_id:  { type: integer }
    prevaccess_id:  { type: integer }
  relations:      
    User:	  { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: UserContent }	
    Directive:    { onDelete: CASCADE, local: directive_id, foreign: id, foreignAlias: DirectiveContent }
    FullAccess:   { class: Ranking, local: fullaccess_id, foreign: id, foreignAlias: RankingFullAccess }
    PrevAccess:	  { class: Ranking, local: prevaccess_id, foreign: id, foreignAlias: RankingPrevAccess }
    
Page:
  actAs: { Timestampable: ~ }
  columns:
    title:         { type: string(255), notnull: true }
    shortdesc:     { type: string(255), notnull: true }
    textbody:      { type: string(2550), notnull: true }
    has_content:   { type: boolean, default: false }

Topic:
  actAs: { Timestampable: ~ }
  columns:
    title:        { type: string(255), notnull: true }
    directive_id: { type: integer, notnull: true }
  relations:
    Directive:    { onDelete: CASCADE, local: directive_id, foreign: id, foreignAlias: DirectiveTopic }

Thread:
  actAs: { Timestampable: ~ }
  columns:
    title:        { type: string(255), notnull: true }
    textbody:     { type: string(2550), notnull: true }
    content_id:   { type: integer }
    topic_id:     { type: integer }
    user_id:	  { type: integer }
  relations:
    Content:      { onDelete: CASCADE, local: content_id, foreign: id, foreignAlias: ContentThread }
    Topic:        { onDelete: CASCADE, local: topic_id, foreign: id, foreignAlias: TopicThread } 
    User:         { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: ThreadAuthor }

Reply:
  actAs: { Timestampable: ~ }
  columns:
    textbody:	  { type: string(2550), notnull: true }
    thread_id:    { type: integer }
    user_id:      { type: integer }
  relations: 
    Thread:       { onDelete: CASCADE, local: thread_id, foreign: id, foreignAlias: ReplyThread }
    User:         { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: ReplyAuthor }

